baseURL: ""
title: Pradeep Loganathan's Blog
pagination:
  pagerSize: 10

  
module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod

languages:
  en-us:
    languageName: English
    weight: 1
