main:
  - name: Search
    pageref: /search
    weight: 10
  - name: Blog
    pageref: /archives
    weight: 20
  - name: slides
    url: /slides
    weight: 30
  - name: Books
    pageref: /books
    weight: 40
  - name: Podcasts
    pageref: /episodes
    weight: 50
  - name: About
    pageref: /about
    weight: 60
