env: production
title: Pradeep Loganathan's Blog
description: My technical notes and thoughts on software engineering, programming, and life.
keywords:
  - Pradeep Loganathan
  - kubernetes
  - Devops
  - GitOps
  - ArgoCD
  - FluxCD

author: Pradeep Loganathan
comments: true
enableSocialMetaTags: true
images:
  - Pradeep-Loganathan.jpeg
  
DateFormat: January 2, 2006
timeFormat: h:mm a
dateTimeFormat: MMMM Do, YYYY h:mm a
language: en-us
languageCode: en-us
mainSections:
  - blog
  - episodes
podcast:
  description: Software engineering podcast - description
  tagline: Software engineering podcast - tagline
  download_url: https://cdn.pradeepl.com/episodes/
  cdn_url: https://cdn.pradeepl.com/
  itunes_url: https://podcasts.apple.com/us/podcast/cloud-native-engineering/id1620074933
  itunes_id: null
  google_podcasts_url: null

editPost:
  URL: https://github.com/PradeepLoganathan/pradeepl-blog/tree/master/content
  Text: "Suggest changes"
  appendFilePath: true

header:
  title: Pradeep Loganathan
  imageUrl: Pradeep-Loganathan.jpeg
  subtitle: cc

label:
  text: Pradeep Loganathan
  icon: Pradeep-Loganathan.jpeg
  iconHeight: 34
  iconWidth: 245
  smallIcon: Pradeep-Loganathan.jpeg
  smallIconHeight: 65
  smallIconWidth: 65

ShowShareButtons: true
ShowReadingTime: true
ShowAuthor: true
ShowBreadCrumbs: true
ShowTags: true
ShowCategories: true
ShowDate: true
ShowPostNavLinks: true
ShowCodeCopyButtons: true
hideFooter: true
ShowRssButtonInSectionTermList: true
ShowFullTextinRSS: true
UseHugoToc: true
ShowToc: true
ShowWordCount: true
defaultTheme: "auto"
disableThemeToggle: false


taxonomies:
  category: categories
  tag: tags
  series: series
  course: course
  episode: episodes

homeInfoParams:
  Title: Hi there ðŸ‘‹
  Content: Welcome to my blog.
  subscribeInfo:
    Text: If you liked this post, check out my other [Featured Posts](/categories/featured) or learn more [About Me](/about).

socialIcons:
  - name: twitter
    url: https://twitter.com/pradeepl
  - name: facebook
    url: https://facebook.com/pradeepl
  - name: linkedin
    url: https://www.linkedin.com/in/pradeeploganathan/
  - name: github
    url: https://github.com/pradeeploganathan
  - name: stackoverflow
    url: https://stackoverflow.com/users/4613054/pradeepl
  - name: rss
    url: /feed.xml

ShowRelatedPosts: true

fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.3
  minMatchCharLength: 0
  keys:
    - title
    - permalink
    - summary
    - content

profileMode:
  enabled: true
  title: Notes from my journey designing and building amazing systems with amazing teams
  subtitle: Software engineering notes
  imageUrl: Pradeep-Loganathan.jpeg
  imageTitle: Pradeep Loganathan
  imageWidth: 120
  imageHeight: 120
  buttons:
    - name: Blog
      url: /blog
    - name: Podcast
      url: /episodes

giscus:
  repo: PradeepLoganathan/pradeepl-blog
  repoID: R_kgDOGrc4sA
  category: BlogPosts
  categoryID: DIC_kwDOGrc4sM4CRM5A
  mapping: pathname
  reactionsEnabled: '1'
  emitMetadata: '0'
  inputPosition: bottom
  theme: preferred_color_scheme
  lang: en
  loading: lazy
opengraph:
  enable: true
  type: "website"
  image: "/Pradeep-Loganathan.jpeg"
  twitter:
    card: "summary_large_image"
